# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-02 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_lat', models.FloatField()),
                ('gps_lon', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('probability', models.FloatField()),
                ('category_name', models.CharField(max_length=20)),
                ('deviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.DeviceID')),
            ],
        ),
    ]
