# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-02 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=30)),
                ('deviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.DeviceID')),
            ],
        ),
    ]
